In [3]:
%load_ext sql

%sql postgresql://postgres:EMvAYOrD%23BYU8y@localhost/political_finance_data
%config SqlMagic.style = 'PLAIN_COLUMNS'
%config SqlMagic.autopandas = True

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [4]:
%%sql
select * from schedule_a_contributions LIMIT 5;

 * postgresql://postgres:***@localhost/political_finance_data
5 rows affected.

,amendment_indicator,amendment_indicator_desc,back_reference_schedule_name,back_reference_transaction_id,candidate_first_name,candidate_id,candidate_last_name,candidate_middle_name,candidate_name,candidate_office,...,recipient_committee_org_type,recipient_committee_type,report_type,report_year,schedule_type,schedule_type_full,sub_id,transaction_id,two_year_transaction_period,unused_contbr_id
0,A,ADD,None,None,None,None,None,None,None,None,...,C,Q,M4,2025,SA,ITEMIZED RECEIPTS,4040320251183188131,IA2747,2026,None
1,A,ADD,None,None,None,None,None,None,None,None,...,C,Q,M4,2025,SA,ITEMIZED RECEIPTS,4040320251183188130,IA2738,2026,None
2,A,ADD,None,None,None,None,None,None,None,None,...,C,Q,M4,2025,SA,ITEMIZED RECEIPTS,4040320251183188129,IA2740,2026,None
3,A,ADD,None,None,None,None,None,None,None,None,...,C,Q,M4,2025,SA,ITEMIZED RECEIPTS,4040320251183188128,IA2744,2026,None
4,A,ADD,None,None,None,None,None,None,None,None,...,C,Q,M4,2025,SA,ITEMIZED RECEIPTS,4040320251183188127,IA2745,2026,None

In [6]:
%%sql
SELECT * FROM committees LIMIT 5;

 * postgresql://postgres:***@localhost/political_finance_data
5 rows affected.

,committee_id,name,designation,designation_full,committee_type,committee_type_full,organization_type,organization_type_full,party,party_full,...,sponsor_committee_type,sponsor_committee_type_full,sponsor_committee_zip,sponsor_name,sponsor_state,sponsor_state_full,sponsor_type,sponsor_type_full,sponsor_zip,terminated
0,C00000000,UFWA COPE COMMITTEE,U,Unauthorized,Q,PAC - Qualified,L,Labor Organization,None,None,...,None,None,None,None,None,None,None,None,None,None
1,C00000018,IRONWORKERS LOCAL UNION NO. 25 POLITICAL EDUCA...,U,Unauthorized,Q,PAC - Qualified,L,Labor Organization,None,None,...,None,None,None,None,None,None,None,None,None,None
2,C00000026,INTERNATIONAL CHIROPRACTORS ASSOCIATION POLITI...,U,Unauthorized,Q,PAC - Qualified,T,Trade Association,UNK,UNKNOWN,...,None,None,None,None,None,None,None,None,None,None
3,C00000042,ILLINOIS TOOL WORKS INC. FOR BETTER GOVERNMENT...,B,Lobbyist/Registrant PAC,Q,PAC - Qualified,C,Corporation,None,None,...,None,None,None,None,None,None,None,None,None,None
4,C00000059,"HALLMARK CARDS, INC. PAC (HALLPAC)",B,Lobbyist/Registrant PAC,Q,PAC - Qualified,C,Corporation,UNK,UNKNOWN,...,None,None,None,None,None,None,None,None,None,None

In [ ]:
results = %sql SELECT contributor_name, contribution_receipt_amount FROM schedule_a_contributions LIMIT 10;
print(results)

 * postgresql://postgres:***@localhost/political_finance_data
10 rows affected.
    contributor_name contribution_receipt_amount
0     RAJA, PRABURAM                      288.45
1   PONNEKANTI, HARI                      300.00
2        PON, JOSEPH                      300.00
3    PATIBANDLA, NAG                      105.00
4  NALAMASU, OMKARAM                      288.45
5       MURPHY, PAUL                      120.00
6   MARRUFO, CHRISTI                      150.00
7        KANIA, JOHN                      115.50
8      JAYARAM, HARI                      300.00
9     HANSON, THOMAS                      115.38